server:
  port: 9198
spring:
  
  application:
    name: APPLICATION_SERVICE
        
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:9999/eureka/

  instance:
    hostname: localhost
